#!/usr/bin/env bash
# Copyright 2026 Cloud-Dog, Viewdeck Engineering Limited
# Licensed under the Apache License, Version 2.0
#
# W28K-1408 NF-1408-1 — inter-spec coverage report.
#
# Emits a route -> spec -> UC-count map for the scheduler-mcp WebUI and flags any
# routed page with no covering Playwright spec. Routes are parsed from
# src/routes/App.tsx; coverage is detected by a spec navigating to the route
# (page.goto("<route>")) or exercising the route's backing /v1 endpoint.
#
# Usage: bash scripts/coverage-report.sh [output.md]   (default: stdout)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
APP_TSX="${APP_DIR}/src/routes/App.tsx"
TESTS_DIR="${APP_DIR}/tests"
OUT="${1:-${APP_DIR}/coverage-report.md}"

# Distinct routed paths (drop the /admin/* aliases that mirror /idam/*).
mapfile -t ROUTES < <(grep -oE '<Route path="[^"]+"' "${APP_TSX}" \
  | sed -E 's/<Route path="([^"]+)"/\1/' \
  | grep -vE '^/admin/' | grep -vE '^\*$' | grep -vE '^/login$' | sort -u)

total_routes=0
covered_routes=0
uncovered=()

emit() { printf '%s\n' "$1" >>"${OUT}"; }

: >"${OUT}"
emit "# W28K-1408 — Inter-spec Coverage Report (NF-1408-1)"
emit ""
emit "Generated by \`scripts/coverage-report.sh\`. Route source: \`src/routes/App.tsx\`."
emit "Spec source: \`tests/*.spec.ts\`. A route is COVERED when a spec navigates to it"
emit "(\`page.goto(\"<route>\")\`) or exercises its backing endpoint."
emit ""
emit "| Route | Covering spec(s) | UC count | Status |"
emit "|---|---|---|---|"

for route in "${ROUTES[@]}"; do
  total_routes=$((total_routes + 1))
  # A route is covered when a spec navigates to it (goto("<route>")) or lists it as
  # a route literal (e.g. the a11y PAGES array: route: "<route>"). Match the exact
  # quoted token so "/" does not match "/schedules".
  pat="(goto\((['\"])${route}(\?|\2)|route:[[:space:]]*(['\"])${route}\4)"
  specs=$(grep -lE "${pat}" "${TESTS_DIR}"/*.spec.ts 2>/dev/null \
    | xargs -r -n1 basename | sort -u | paste -sd ',' - || true)
  if [[ -z "${specs}" ]]; then
    uc=0
    uncovered+=("${route}")
    status="UNCOVERED"
  else
    uc=$(grep -hcE "${pat}" "${TESTS_DIR}"/*.spec.ts 2>/dev/null | paste -sd '+' - | bc 2>/dev/null || echo "?")
    covered_routes=$((covered_routes + 1))
    status="covered"
  fi
  emit "| \`${route}\` | ${specs:-—} | ${uc} | ${status} |"
done

emit ""
emit "## Spec inventory"
emit ""
emit "| Spec | test() blocks |"
emit "|---|---|"
for spec in "${TESTS_DIR}"/*.spec.ts; do
  [[ -e "${spec}" ]] || continue
  n=$(grep -cE "^\s*test\(" "${spec}" || true)
  emit "| $(basename "${spec}") | ${n} |"
done

emit ""
emit "## Summary"
emit ""
emit "- Routes total: **${total_routes}**"
emit "- Routes covered: **${covered_routes}**"
if [[ ${#uncovered[@]} -eq 0 ]]; then
  emit "- Uncovered routes: **0** — every routed page has a covering spec."
else
  emit "- Uncovered routes (**${#uncovered[@]}**): ${uncovered[*]}"
fi

echo "[coverage-report] wrote ${OUT} (covered ${covered_routes}/${total_routes})" >&2
